export type ShowcaseToken = readonly [
  'keyword' | 'storage' | 'plain' | 'operator' | 'function' | 'punctuation' | 'string' | 'comment' | 'number',
  string,
]

export const showcaseCode = [
  ['storage', 'const'],
  ['plain', ' prophecy '],
  ['operator', '='],
  ['plain', ' '],
  ['function', 'await awaken'],
  ['punctuation', '('],
  ['string', '"Ironwood"'],
  ['punctuation', ')'],
  ['plain', ''],
  ['comment', '// Build softly. Ship boldly.'],
  ['keyword', 'if'],
  ['plain', ' '],
  ['punctuation', '('],
  ['plain', 'prophecy'],
  ['punctuation', '.'],
  ['plain', 'isReady'],
  ['punctuation', ') {'],
  ['plain', ''],
  ['plain', '  '],
  ['function', 'release'],
  ['punctuation', '('],
  ['number', '3'],
  ['punctuation', ')'],
  ['plain', ''],
  ['punctuation', '}'],
] as const satisfies readonly ShowcaseToken[]
